#Spring config
spring:
  application:
    name: securebanking-openbanking-uk-rs
  data:
    mongodb:
      database: mongo

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.forgerock: DEBUG

# Configuration for calling the Consent Repository
# See: com.forgerock.sapi.gateway.ob.uk.rs.cloud.client.configuration.ConsentRepoConfiguration
consent:
  repo:
    contexts_repo_consent:
      get: /repo/consents/@IntentId@
      put: /repo/consents/@IntentId@
      patch: /repo/consents/@IntentId@
      delete: /repo/consents/@IntentId@

# RS config
rs:
  # Data creation limits (see com.forgerock.securebanking.openbanking.uk.rs.api.admin.data.DataCreator)
  data:
    upload:
      limit:
        accounts: 100
        documents: 1000

# Configuration for testdata used by the Bank Simulator
testdata:
  # Configure Account Identifier for test users, if config is not provided for a particular user then randomised data is used
  # See com.forgerock.sapi.gateway.ob.uk.rs.server.configuration.TestUserAccountIds
  userAccountIds:
    psu4test:
      - sortCode: "012332"
        accountNumber: "43245676"
      - sortCode: "012332"
        accountNumber: "54312390"
      - sortCode: "334412"
        accountNumber: "30187862"

#
# Deployment Specific configuration
# The following section contains the mandatory configuration that is deployment specific.
#
#
# Consent Repo Configuration
#consent:
#  repo:
#    # Connection string to the Consent Repo base URI
#    uri:
#