#
# Deployment Specific configuration
#
# The following section is a template of the mandatory configuration that needs to be supplied in order to start the
# application, this config is deployment specific.
#
#
# Cloud Client API settings
#cloud:
#  client:
#    # Connection string to connect to the Cloud Data API
#    baseUri:
#
#rs:
#  discovery:
#    Open Banking Organisation Id of the ASPSP running the RS
#    financialId:
#
#
# RCS Consent Store API configuration
#rcs:
#  consent:
#    store:
#      api:
#        # baseUri to the RCS Consent Store API
#        baseUri:

server:
  max-http-header-size: 16KB

spring:
  data:
    mongodb:
      database: test-facility-bank

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.forgerock: DEBUG
    uk.org.openbanking: DEBUG

# Configuration for calling the Cloud Data API
# com.forgerock.sapi.gateway.ob.uk.rs.cloud.client.configuration.CloudClientConfiguration
cloud:
  client:
    contexts_user:
      get: /repo/users/@UserId@
      put: /repo/users/@UserId@
      patch: /repo/users/@UserId@
      delete: /repo/users/@UserId@

# RS config
rs:
  # Data creation limits
  # see com.forgerock.securebanking.openbanking.uk.rs.api.admin.data.DataCreator
  # see com.forgerock.sapi.gateway.rs.resource.store.api.admin.events.DataEventsApiController
  data:
    upload:
      limit:
        accounts: 100
        documents: 1000
        events: 10
  obie:
    validation:
      # OBIE validation module to load, the "default" module is provided as standard with the simulator
      module: default
      config:
        payments:
          # Controls whether the optional schema field in payment consents: consent.risk.paymentContextCode should be made mandatory
          requirePaymentContextCode: false
  # Exchange rate values to use in FX quotes
  exchange:
    rates:
      default: "1.5123"
      pairs:
        GBPUSD: "1.3211"
        GBPEUR: "1.1634"

