#
# Deployment Specific configuration
#
# The following section is a template of the mandatory configuration that needs to be supplied in order to start the
# application, this config is deployment specific.
#
#
# Consent Repo Configuration
#consent:
#  repo:
#    # Connection string to the Consent Repo base URI
#    uri:
#
#rs:
#  discovery:
#    Open Banking Organisation Id of the ASPSP running the RS
#    financialId:
#
#
# RCS Consent Store API configuration
#rcs:
#  consent:
#    store:
#      api:
#        # baseUri to the RCS Consent Store API
#        baseUri:

spring:
  data:
    mongodb:
      database: test-facility-bank

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.forgerock: DEBUG
    uk.org.openbanking: DEBUG

# Configuration for calling the Consent Repository
# See: com.forgerock.sapi.gateway.ob.uk.rs.cloud.client.configuration.ConsentRepoConfiguration
consent:
  repo:
    contexts_repo_consent:
      get: /repo/consents/@IntentId@
      put: /repo/consents/@IntentId@
      patch: /repo/consents/@IntentId@
      delete: /repo/consents/@IntentId@
    contexts_user:
      get: /repo/users/@UserId@
      put: /repo/users/@UserId@
      patch: /repo/users/@UserId@
      delete: /repo/users/@UserId@

# RS config
rs:
  # Data creation limits (see com.forgerock.securebanking.openbanking.uk.rs.api.admin.data.DataCreator)
  data:
    upload:
      limit:
        accounts: 100
        documents: 1000
  obie:
    validation:
      # OBIE validation module to load, the "default" module is provided as standard with the simulator
      module: default
