/*
 * Copyright © 2020-2024 ForgeRock AS (obst@forgerock.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.forgerock.sapi.gateway.ob.uk.rs.obie.api.account.v3_1_11.directdebits;

import org.springframework.web.bind.annotation.RequestMapping;

import com.forgerock.sapi.gateway.ob.uk.rs.obie.api.swagger.SwaggerApiTags;

import io.swagger.annotations.Api;

@Api(tags = {"v3.1.11", SwaggerApiTags.ACCOUNTS_AND_TRANSACTION_TAG})
@RequestMapping(value = "/open-banking/v3.1.11/aisp")
public interface DirectDebitsApi extends com.forgerock.sapi.gateway.ob.uk.rs.obie.api.account.v3_1_10.directdebits.DirectDebitsApi {
}
