version: '3.8'
services:

  securebanking-config-server:
    container_name: securebanking-config-server
    image: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-spring-config-server
    environment:
      - SSH_KEY=${GIT_SSH_KEY}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=git@github.com:SecureApiGateway/secure-api-gateway-ob-uk-spring-config.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL=master
    ports:
      - 8888:8888

  rs-simulator:
    container_name: rs-simulator
    image: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-openbanking-uk-rs
    ports:
      - 8080:8080
      - 9096:9096
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://securebanking-config-server:8888
      - SPRING_DATA_MONGODB_HOST=rs-mongo
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:9096,server=y,suspend=n
    command: /app/wait-for.sh securebanking-config-server:8888 -- java -jar securebanking-openbanking-uk-rs.jar
    restart: on-failure
    depends_on:
      - rs-mongo
      - securebanking-config-server
    links:
      - rs-mongo
      - securebanking-config-server

  rs-mongo:
    container_name: rs-mongo
    image: mongo:4.4.2
    ports:
      - 27017:27017
    volumes:
    - ./.mongo/data:/data/db
