version: '3.8'
services:

  securebanking-config-server:
    container_name: securebanking-config-server
    hostname: securebanking-config-server
    image: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-spring-config-server
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - CONFIG_SERVER_SEARCH_LOCATIONS=file:///home/config
    ports:
      - 8888:8888
    volumes:
      - ./config:/home/config

  rs-simulator:
    container_name: rs-simulator
    image: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-openbanking-uk-rs
    ports:
      - 8080:8080
      - 9096:9096
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://securebanking-config-server:8888
      - SPRING_DATA_MONGODB_HOST=rs-mongo
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:9096,server=y,suspend=n
    command: /app/wait-for.sh securebanking-config-server:8888 -- java -jar securebanking-openbanking-uk-rs.jar
    restart: on-failure
    depends_on:
      - rs-mongo
      - securebanking-config-server
    links:
      - rs-mongo
      - securebanking-config-server

  rs-mongo:
    container_name: rs-mongo
    image: mongo:4.4.2
    ports:
      - 27017:27017
    volumes:
    - ./.mongo/data:/data/db
