---
{{- if .Values.springConfig -}}
apiVersion: {{ .Values.configmap.apiVersion }}
kind: ConfigMap
metadata:
  name: application-config
  labels:
    app: {{ .Chart.Name }}
data:
  application.yml: | {{ tpl (toYaml .Values.springConfig) . | nindent 4 }}
{{- end }}
