apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.deployment.imageOverride.enabled }}
          image: "{{ .Values.deployment.imageOverride.repo }}{{ .Values.deployment.imageOverride.tagDelimiter }}{{ .Values.deployment.imageOverride.tag }}"
          {{- else }}
          image: "eu.gcr.io/sbat-gcr-release/securebanking/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - name: http-server
              containerPort: {{ .Values.deployment.server.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.deployment.server.port }}
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.deployment.server.port }}
            initialDelaySeconds: 160
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
          - name: SPRING_DATA_MONGODB_HOST
            value: {{ .Values.mongodb.host }}
          - name: SERVER_PORT
            value: {{ .Values.deployment.server.port | quote }}
          - name: CONSENT_REPO_URI
            valueFrom:
              configMapKeyRef:
                name: securebanking-platform-config
                key: CONSENT_REPO_URI
          - name: RS_DISCOVERY_FINANCIAL_ID
            valueFrom:
              configMapKeyRef:
                name: securebanking-platform-config
                key: OB_ASPSP_ORG_ID
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: JAVA_OPTS
            value: {{ .Values.deployment.java.opts }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
