#Spring config
spring:
  cloud:
    config:
      uri: http://securebanking-config-server:8888
      failFast: true
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
  application:
    name: securebanking-openbanking-uk-rs
  profiles:
    active: NOT_SET

#Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
