deployment:
  apiVersion: apps/v1
  replicas: 1

  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 25%

  imagePullPolicy: Always

  # Deploy a different image to the intended release (useful for development)
  imageOverride:
    enabled: true
    repo: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-openbanking-uk-rs
    tag: latest
    tagDelimiter: ":"

  server:
    port: 8080

  java:
    opts: -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=50 -agentlib:jdwp=transport=dt_socket,address=*:9090,server=y,suspend=n
    
  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 1
      memory: 1024Mi

mongodb:
  host: mongodb
  
service:
  apiVersion: v1
  type: ClusterIP

