name: Merge - Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ob-v*
    paths-ignore:
      - '**/README.md'
      - '../../../secure-api-gateway-core/_infra/helm/**'
jobs:
  run_pr-template:
    name: Merge - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-merge.yml@main
    secrets: inherit
    with:
      componentBranch: ${{ github.head_ref || github.ref_name }}
      componentName: secure-api-gateway-ob-uk-rs
      dockerTag: $(echo ${{ github.sha }} | cut -c1-7)