name: merge-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: securebanking-openbanking-uk-rs

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check master integrity
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/pom.xml') }}

      - name: test
        run: |
          make verify

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true

      - run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          make docker repo=${{ secrets.RELEASE_REPO }}

      - name: helm version
        id: helm
        run: |
          HELM_VERSION=$(make version)
          echo ::set-output name=version::"$HELM_VERSION"

      - name: package helm
        run: |
          make helm version=${{ steps.helm.outputs.version }}

      - name: Publish Release Chart 
        id: upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.SERVICE_NAME }}-${{ steps.helm.outputs.version }}.tgz
          destination: ${{ secrets.HELM_RELEASE_BUCKET }}/${{ env.SERVICE_NAME }}

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
