name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  HELM_DIRECTORY: _infra/helm/
  SERVICE_NAME: securebanking-openbanking-uk-rs

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/pom.xml') }}

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}

      - name: template helm
        run: |
          helm template $HELM_DIRECTORY/$SERVICE_NAME

      - name: package helm
        run: |
          echo HELM_VERSION=$(grep -E "version:\s+" $HELM_DIRECTORY/$SERVICE_NAME/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g') >> $GITHUB_ENV
          helm dep up $HELM_DIRECTORY/$SERVICE_NAME
          helm package $HELM_DIRECTORY/$SERVICE_NAME

      - name: Publish PR Chart
        run: |
          mv $SERVICE_NAME-${{ env.HELM_VERSION }}.tgz $SERVICE_NAME-latest.tgz
          gsutil cp $SERVICE_NAME-*.tgz gs://${{ secrets.HELM_DEV_BUCKET }}/$SERVICE_NAME/

      - name: Check Copyright
        run: mvn license:check

      - name: Build
        run: |
          mvn -B clean package -DskipTests -DskipITs -DdockerCompose.skip -Ddockerfile.skip --file pom.xml

      - run: |
          gcloud auth configure-docker

      - name: pr docker tag
        id: tag
        run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "$PR"
          echo ::set-output name=pr_number::pr-"$PR"

      - name: Build Docker Image
        run: |
          make docker tag=${{ steps.tag.outputs.pr_number }}

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
