name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: securebanking-openbanking-uk-rs

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/pom.xml') }}

      - name: Check Copyright
        run: mvn license:check

      - name: test
        run: |
          make verify
      
      - name: output PR tags
        id: tags
        run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo ::set-output name=pr_number::pr-"$PR"

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true

      - run: |
          gcloud auth configure-docker

      - name: pr docker tag
        id: tag
        run: |
          PR=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "$PR"
          echo ::set-output name=pr_number::pr-"$PR"

      - name: Build Docker Image
        run: |
          make docker tag=${{ steps.tag.outputs.pr_number }}

      - name: package helm
        run: |
          make helm version=${{ steps.tag.outputs.pr_number }}

      - name: Publish PR Chart
        id: upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.SERVICE_NAME }}-${{ steps.tag.outputs.pr_number }}.tgz
          destination: ${{ secrets.HELM_DEV_BUCKET }}/${{ env.SERVICE_NAME }}/

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
