name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  HELM_DIRECTORY: _infra/helm/
  SERVICE_NAME: securebanking-openbanking-uk-rs
  PR_NUMBER: pr-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven2-${{ hashFiles('**/pom.xml') }}
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
      
      - name: template helm
        run: |
          helm template $HELM_DIRECTORY/$SERVICE_NAME

      - name: Check Copyright
        run: mvn license:check

      - name: test
        run: |
          make verify
      
      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          make docker tag=${{ env.PR_NUMBER }}
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/${{ env.SERVICE_NAME}}:{{ github.sha }} eu.gcr.io/${{ secrets.DEV_REPO }}:latest
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/${{ env.SERVICE_NAME}}:latest

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
      
      - name: 'run functional tests'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v TAG=${{ env.PR_NUMBER }} -v SERVICE_NAME=rs -v ENVIRONMENT=${{ github.actor }} -v BRANCH=${{ github.head_ref }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        id: run-pipeline
