name: create-release
run-name: Create release '${{ inputs.release_version_number }}'
# What it does:
# - Call release-prepare workflow
# - Call release-publish-java workflow
# - Call release-publish-docker workflow
# - Call release-publish-helm workflow
# - Call release-publish-draft-and-pr
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string

jobs:
  release_prepare: # prepare for a release in scm, creates the tag and release branch with the proper release versions
    name: Call release prepare
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-prepare.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      github_release_user: ${{ vars.GIT_RELEASE_USER }}
      github_release_email: ${{ vars.GIT_RELEASE_EMAIL }}
    secrets:
      release_github_token: ${{ secrets.RELEASE_PAT }}

  release_java:
    name: Call publish java
    needs: [ release_prepare ]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-java.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
    secrets:
      FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
      FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

  release_docker:
    name: Call publish docker
    needs: [ release_prepare, release_java ]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-docker.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
      SERVICE_NAME: securebanking-openbanking-uk-rs
      GAR_RELEASE_REPO: ${{ vars.GAR_RELEASE_REPO }}

    secrets:
      GCR_CREDENTIALS_JSON: ${{ secrets.DEV_GAR_KEY }}

  release_helm:
    name: Call publish helm
    needs: [ release_prepare, release_java ]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-helm.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
      root_helm_directory: "_infra/helm/securebanking-openbanking-uk-rs"
    secrets:
      FR_ARTIFACTORY_USER_ACCESS_TOKEN: ${{ secrets.FR_ARTIFACTORY_USER_ACCESS_TOKEN }}
      FR_HELM_REPO: ${{ secrets.FR_HELM_REPO }}

  release_publish:
    name: Call publish
    needs: [ release_prepare, release_java, release_docker, release_helm ]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
      release_notes: ${{ inputs.notes }}
    secrets:
      release_github_token: ${{ secrets.RELEASE_PAT }}